In [70]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name":['krunal','jayraj','sidh','jaimin','anand'],
    "marks":['79','60','50','55','56'],
    "city":['ahmedabad','halvad','morbi','ranjitgadh','halvad']
}

In [3]:
df=pd.DataFrame(dict1)

In [4]:
df

     name marks        city
0  krunal    79   ahmedabad
1  jayraj    60      halvad
2    sidh    50       morbi
3  jaimin    55  ranjitgadh
4   anand    56      halvad

In [5]:
df.to_csv('friend_csv')

In [6]:
df.to_csv('friend_index_false).csv', index=False)

In [7]:
df.head(2)

     name marks       city
0  krunal    79  ahmedabad
1  jayraj    60     halvad

In [8]:
df.tail(1)

    name marks    city
4  anand    56  halvad

In [9]:
df.describe()

          name marks    city
count        5     5       5
unique       5     5       4
top     krunal    79  halvad
freq         1     1       2

In [10]:
krunal = pd.read_csv('krunal.csv')
krunal

   train no  speed        city
0      1644     79   ahmedabad
1      1264     60      halvad
2      1252     50       morbi
3      1265     55  ranjitgadh
4      1452     56      halvad

In [11]:
krunal['speed'][0]=85

C:\Users\kruna\AppData\Local\Temp\ipykernel_12156\3941767984.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  krunal['speed'][0]=85

In [12]:
krunal

   train no  speed        city
0      1644     79   ahmedabad
1      1264     60      halvad
2      1252     50       morbi
3      1265     55  ranjitgadh
4      1452     56      halvad

In [13]:
krunal.to_csv

<bound method NDFrame.to_csv of    train no  speed        city
0      1644     79   ahmedabad
1      1264     60      halvad
2      1252     50       morbi
3      1265     55  ranjitgadh
4      1452     56      halvad>

krunal.index = ['four','five','six','seven','eight']

In [14]:
krunal

   train no  speed        city
0      1644     79   ahmedabad
1      1264     60      halvad
2      1252     50       morbi
3      1265     55  ranjitgadh
4      1452     56      halvad

In [15]:
ser = pd.Series(np.random.rand(25))

In [16]:
ser

0     0.917031
1     0.522538
2     0.499834
3     0.247415
4     0.827334
5     0.776887
6     0.709132
7     0.935453
8     0.026100
9     0.040429
10    0.589164
11    0.089917
12    0.554783
13    0.837277
14    0.583380
15    0.858916
16    0.452010
17    0.607418
18    0.347937
19    0.416717
20    0.571979
21    0.976239
22    0.846711
23    0.793909
24    0.744680
dtype: float64

In [17]:
type(ser)

pandas.Series

In [18]:
newdf = pd.DataFrame(np.random.rand(221,5),index = np.arange(221))

In [19]:
newdf

            0         1         2         3         4
0    0.679922  0.198703  0.382484  0.788295  0.746294
1    0.871185  0.524304  0.857125  0.644504  0.574060
2    0.980907  0.080592  0.495087  0.867326  0.750801
3    0.002225  0.503149  0.546715  0.434636  0.826405
4    0.483683  0.763482  0.973455  0.830068  0.735215
..        ...       ...       ...       ...       ...
216  0.704472  0.698501  0.711056  0.647427  0.732279
217  0.862461  0.213811  0.896249  0.277109  0.673619
218  0.815203  0.783656  0.423769  0.064249  0.760220
219  0.304523  0.343384  0.519712  0.333602  0.199461
220  0.745247  0.409209  0.370460  0.525673  0.931763

[221 rows x 5 columns]

In [20]:
newdf.head()

          0         1         2         3         4
0  0.679922  0.198703  0.382484  0.788295  0.746294
1  0.871185  0.524304  0.857125  0.644504  0.574060
2  0.980907  0.080592  0.495087  0.867326  0.750801
3  0.002225  0.503149  0.546715  0.434636  0.826405
4  0.483683  0.763482  0.973455  0.830068  0.735215

In [21]:
newdf.describe()

                0           1           2           3           4
count  221.000000  221.000000  221.000000  221.000000  221.000000
mean     0.528459    0.498564    0.468503    0.491572    0.515503
std      0.290109    0.303653    0.282880    0.276431    0.293853
min      0.002225    0.003197    0.001960    0.000845    0.002338
25%      0.278214    0.248467    0.219099    0.277109    0.246679
50%      0.507718    0.446181    0.469039    0.476139    0.564906
75%      0.785988    0.783656    0.698320    0.704160    0.752722
max      0.998875    0.996086    0.994209    0.999304    0.999564

type(newdf)

In [22]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [23]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [24]:
newdf.head()

          0         1         2         3         4
0  0.679922  0.198703  0.382484  0.788295  0.746294
1  0.871185  0.524304  0.857125  0.644504  0.574060
2  0.980907  0.080592  0.495087  0.867326  0.750801
3  0.002225  0.503149  0.546715  0.434636  0.826405
4  0.483683  0.763482  0.973455  0.830068  0.735215

In [25]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       211, 212, 213, 214, 215, 216, 217, 218, 219, 220],
      dtype='int64', length=221)

In [26]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [27]:
newdf.to_numpy()

array([[0.67992201, 0.19870333, 0.3824841 , 0.78829522, 0.74629407],
       [0.87118531, 0.52430356, 0.85712528, 0.6445041 , 0.57405996],
       [0.98090696, 0.08059181, 0.49508681, 0.86732575, 0.75080142],
       ...,
       [0.81520305, 0.7836557 , 0.42376911, 0.0642486 , 0.76021959],
       [0.30452271, 0.34338371, 0.51971204, 0.33360224, 0.19946097],
       [0.74524685, 0.40920873, 0.37046048, 0.52567281, 0.93176328]],
      shape=(221, 5))

In [28]:
newdf[0][0] = 0.45

C:\Users\kruna\AppData\Local\Temp\ipykernel_12156\2499507120.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  newdf[0][0] = 0.45

In [29]:
newdf.head()

          0         1         2         3         4
0  0.679922  0.198703  0.382484  0.788295  0.746294
1  0.871185  0.524304  0.857125  0.644504  0.574060
2  0.980907  0.080592  0.495087  0.867326  0.750801
3  0.002225  0.503149  0.546715  0.434636  0.826405
4  0.483683  0.763482  0.973455  0.830068  0.735215

In [30]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,211,212,213,214,215,216,217,218,219,220
0,0.679922,0.871185,0.980907,0.002225,0.483683,0.942042,0.475248,0.362965,0.110497,0.120797,...,0.217073,0.381939,0.293409,0.382113,0.978257,0.704472,0.862461,0.815203,0.304523,0.745247
1,0.198703,0.524304,0.080592,0.503149,0.763482,0.899506,0.778589,0.951992,0.293670,0.962995,...,0.255115,0.992542,0.930786,0.288259,0.158831,0.698501,0.213811,0.783656,0.343384,0.409209
2,0.382484,0.857125,0.495087,0.546715,0.973455,0.711576,0.994209,0.746591,0.636798,0.842799,...,0.391489,0.109317,0.518139,0.792583,0.972564,0.711056,0.896249,0.423769,0.519712,0.370460
3,0.788295,0.644504,0.867326,0.434636,0.830068,0.417602,0.402726,0.765661,0.471073,0.996153,...,0.464940,0.274872,0.453086,0.487439,0.777181,0.647427,0.277109,0.064249,0.333602,0.525673
4,0.746294,0.574060,0.750801,0.826405,0.735215,0.803735,0.695572,0.155705,0.213919,0.028872,...,0.048595,0.931741,0.186493,0.918732,0.473006,0.732279,0.673619,0.760220,0.199461,0.931763

In [31]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.746294  0.788295  0.382484  0.198703  0.679922
1    0.574060  0.644504  0.857125  0.524304  0.871185
2    0.750801  0.867326  0.495087  0.080592  0.980907
3    0.826405  0.434636  0.546715  0.503149  0.002225
4    0.735215  0.830068  0.973455  0.763482  0.483683
..        ...       ...       ...       ...       ...
216  0.732279  0.647427  0.711056  0.698501  0.704472
217  0.673619  0.277109  0.896249  0.213811  0.862461
218  0.760220  0.064249  0.423769  0.783656  0.815203
219  0.199461  0.333602  0.519712  0.343384  0.304523
220  0.931763  0.525673  0.370460  0.409209  0.745247

[221 rows x 5 columns]

In [32]:
newdf.sort_index(ascending = True)

            0         1         2         3         4
0    0.679922  0.198703  0.382484  0.788295  0.746294
1    0.871185  0.524304  0.857125  0.644504  0.574060
2    0.980907  0.080592  0.495087  0.867326  0.750801
3    0.002225  0.503149  0.546715  0.434636  0.826405
4    0.483683  0.763482  0.973455  0.830068  0.735215
..        ...       ...       ...       ...       ...
216  0.704472  0.698501  0.711056  0.647427  0.732279
217  0.862461  0.213811  0.896249  0.277109  0.673619
218  0.815203  0.783656  0.423769  0.064249  0.760220
219  0.304523  0.343384  0.519712  0.333602  0.199461
220  0.745247  0.409209  0.370460  0.525673  0.931763

[221 rows x 5 columns]

In [33]:
newdf.head()

          0         1         2         3         4
0  0.679922  0.198703  0.382484  0.788295  0.746294
1  0.871185  0.524304  0.857125  0.644504  0.574060
2  0.980907  0.080592  0.495087  0.867326  0.750801
3  0.002225  0.503149  0.546715  0.434636  0.826405
4  0.483683  0.763482  0.973455  0.830068  0.735215

In [34]:
newdf[0]

0      0.679922
1      0.871185
2      0.980907
3      0.002225
4      0.483683
         ...
216    0.704472
217    0.862461
218    0.815203
219    0.304523
220    0.745247
Name: 0, Length: 221, dtype: float64

In [35]:
type(newdf[0])

pandas.Series

In [36]:
newdf2=newdf

In [37]:
newdf2[0][0] = 1545

C:\Users\kruna\AppData\Local\Temp\ipykernel_12156\749720841.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  newdf2[0][0] = 1545

In [38]:
newdf

            0         1         2         3         4
0    0.679922  0.198703  0.382484  0.788295  0.746294
1    0.871185  0.524304  0.857125  0.644504  0.574060
2    0.980907  0.080592  0.495087  0.867326  0.750801
3    0.002225  0.503149  0.546715  0.434636  0.826405
4    0.483683  0.763482  0.973455  0.830068  0.735215
..        ...       ...       ...       ...       ...
216  0.704472  0.698501  0.711056  0.647427  0.732279
217  0.862461  0.213811  0.896249  0.277109  0.673619
218  0.815203  0.783656  0.423769  0.064249  0.760220
219  0.304523  0.343384  0.519712  0.333602  0.199461
220  0.745247  0.409209  0.370460  0.525673  0.931763

[221 rows x 5 columns]

In [39]:
newdf.loc[0,0]= 1452

In [40]:
newdf.head(1)

        0         1         2         3         4
0  1452.0  0.198703  0.382484  0.788295  0.746294

In [41]:
newdf.columns=list("KLMNO")

In [42]:
newdf

               K         L         M         N         O
0    1452.000000  0.198703  0.382484  0.788295  0.746294
1       0.871185  0.524304  0.857125  0.644504  0.574060
2       0.980907  0.080592  0.495087  0.867326  0.750801
3       0.002225  0.503149  0.546715  0.434636  0.826405
4       0.483683  0.763482  0.973455  0.830068  0.735215
..           ...       ...       ...       ...       ...
216     0.704472  0.698501  0.711056  0.647427  0.732279
217     0.862461  0.213811  0.896249  0.277109  0.673619
218     0.815203  0.783656  0.423769  0.064249  0.760220
219     0.304523  0.343384  0.519712  0.333602  0.199461
220     0.745247  0.409209  0.370460  0.525673  0.931763

[221 rows x 5 columns]

In [43]:
newdf[0,0]=1542

In [44]:
newdf.head()

             K         L         M         N         O  (0, 0)
0  1452.000000  0.198703  0.382484  0.788295  0.746294    1542
1     0.871185  0.524304  0.857125  0.644504  0.574060    1542
2     0.980907  0.080592  0.495087  0.867326  0.750801    1542
3     0.002225  0.503149  0.546715  0.434636  0.826405    1542
4     0.483683  0.763482  0.973455  0.830068  0.735215    1542

In [45]:
newdf[0,'O']=1212

In [46]:
newdf.head()

             K         L         M         N         O  (0, 0)  (0, O)
0  1452.000000  0.198703  0.382484  0.788295  0.746294    1542    1212
1     0.871185  0.524304  0.857125  0.644504  0.574060    1542    1212
2     0.980907  0.080592  0.495087  0.867326  0.750801    1542    1212
3     0.002225  0.503149  0.546715  0.434636  0.826405    1542    1212
4     0.483683  0.763482  0.973455  0.830068  0.735215    1542    1212

In [47]:
newdf.loc[[0,1],['K','M']]

             K         M
0  1452.000000  0.382484
1     0.871185  0.857125

In [48]:
newdf.head()

             K         L         M         N         O  (0, 0)  (0, O)
0  1452.000000  0.198703  0.382484  0.788295  0.746294    1542    1212
1     0.871185  0.524304  0.857125  0.644504  0.574060    1542    1212
2     0.980907  0.080592  0.495087  0.867326  0.750801    1542    1212
3     0.002225  0.503149  0.546715  0.434636  0.826405    1542    1212
4     0.483683  0.763482  0.973455  0.830068  0.735215    1542    1212

In [49]:
newdf.loc[[0,1],:]

             K         L         M         N         O  (0, 0)  (0, O)
0  1452.000000  0.198703  0.382484  0.788295  0.746294    1542    1212
1     0.871185  0.524304  0.857125  0.644504  0.574060    1542    1212

In [50]:
newdf.loc[(newdf['K']<0.3)& (newdf['O']>0.2)]

            K         L         M         N         O  (0, 0)  (0, O)
3    0.002225  0.503149  0.546715  0.434636  0.826405    1542    1212
8    0.110497  0.293670  0.636798  0.471073  0.213919    1542    1212
11   0.248939  0.747264  0.925242  0.709734  0.917855    1542    1212
19   0.295589  0.857011  0.240510  0.398333  0.923756    1542    1212
20   0.139985  0.572681  0.908584  0.581269  0.404604    1542    1212
22   0.194456  0.313753  0.289150  0.464659  0.947140    1542    1212
33   0.114114  0.446181  0.557471  0.011312  0.253342    1542    1212
36   0.134124  0.328350  0.331724  0.855685  0.741513    1542    1212
45   0.215248  0.549989  0.356272  0.141028  0.929957    1542    1212
46   0.220830  0.777279  0.467578  0.677163  0.277270    1542    1212
49   0.053764  0.976147  0.264830  0.204643  0.578707    1542    1212
59   0.162747  0.962649  0.383811  0.476139  0.794669    1542    1212
61   0.103612  0.774887  0.937445  0.104721  0.628416    1542    1212
68   0.129996  0.804248  0.810519  0.313666  0.874970    1542    1212
72   0.278214  0.363645  0.377523  0.269837  0.578788    1542    1212
76   0.216601  0.278783  0.697194  0.635735  0.753438    1542    1212
80   0.117780  0.445934  0.815645  0.300256  0.498521    1542    1212
83   0.046253  0.642433  0.614400  0.550796  0.401600    1542    1212
84   0.027311  0.184332  0.784447  0.999304  0.702892    1542    1212
88   0.201354  0.586937  0.070174  0.599233  0.261077    1542    1212
101  0.216992  0.784697  0.465924  0.373616  0.323705    1542    1212
106  0.013671  0.494691  0.533602  0.948908  0.575645    1542    1212
128  0.282911  0.927372  0.206579  0.279031  0.564906    1542    1212
140  0.115433  0.268807  0.115943  0.924771  0.316164    1542    1212
149  0.097119  0.828372  0.105013  0.680154  0.263109    1542    1212
150  0.209067  0.438434  0.433357  0.904436  0.651423    1542    1212
152  0.063145  0.626709  0.259033  0.195683  0.827304    1542    1212
167  0.026183  0.219178  0.440702  0.558381  0.388592    1542    1212
176  0.147640  0.545477  0.093606  0.198527  0.582907    1542    1212
183  0.211826  0.061526  0.229076  0.225020  0.509068    1542    1212
190  0.015392  0.787685  0.518630  0.327242  0.820584    1542    1212
191  0.096104  0.165130  0.500973  0.778849  0.744607    1542    1212
194  0.260808  0.663336  0.764489  0.736874  0.871761    1542    1212
195  0.184767  0.781391  0.070982  0.389453  0.650235    1542    1212
196  0.061330  0.137000  0.909343  0.755431  0.873033    1542    1212
198  0.208034  0.003748  0.022884  0.288742  0.945909    1542    1212
204  0.242269  0.901132  0.850542  0.695496  0.230160    1542    1212
209  0.137293  0.927749  0.059809  0.378667  0.763246    1542    1212

In [51]:
newdf.head(2)

             K         L         M         N         O  (0, 0)  (0, O)
0  1452.000000  0.198703  0.382484  0.788295  0.746294    1542    1212
1     0.871185  0.524304  0.857125  0.644504  0.574060    1542    1212

In [52]:
newdf.iloc[0,4]

np.float64(0.7462940746268371)

In [53]:
newdf.iloc[[0,5],[1,2]]

          L         M
0  0.198703  0.382484
5  0.899506  0.711576

In [54]:
newdf.head(5)

             K         L         M         N         O  (0, 0)  (0, O)
0  1452.000000  0.198703  0.382484  0.788295  0.746294    1542    1212
1     0.871185  0.524304  0.857125  0.644504  0.574060    1542    1212
2     0.980907  0.080592  0.495087  0.867326  0.750801    1542    1212
3     0.002225  0.503149  0.546715  0.434636  0.826405    1542    1212
4     0.483683  0.763482  0.973455  0.830068  0.735215    1542    1212

In [55]:
newdf.drop([0])

            K         L         M         N         O  (0, 0)  (0, O)
1    0.871185  0.524304  0.857125  0.644504  0.574060    1542    1212
2    0.980907  0.080592  0.495087  0.867326  0.750801    1542    1212
3    0.002225  0.503149  0.546715  0.434636  0.826405    1542    1212
4    0.483683  0.763482  0.973455  0.830068  0.735215    1542    1212
5    0.942042  0.899506  0.711576  0.417602  0.803735    1542    1212
..        ...       ...       ...       ...       ...     ...     ...
216  0.704472  0.698501  0.711056  0.647427  0.732279    1542    1212
217  0.862461  0.213811  0.896249  0.277109  0.673619    1542    1212
218  0.815203  0.783656  0.423769  0.064249  0.760220    1542    1212
219  0.304523  0.343384  0.519712  0.333602  0.199461    1542    1212
220  0.745247  0.409209  0.370460  0.525673  0.931763    1542    1212

[220 rows x 7 columns]

In [56]:
newdf.head(10)

             K         L         M         N         O  (0, 0)  (0, O)
0  1452.000000  0.198703  0.382484  0.788295  0.746294    1542    1212
1     0.871185  0.524304  0.857125  0.644504  0.574060    1542    1212
2     0.980907  0.080592  0.495087  0.867326  0.750801    1542    1212
3     0.002225  0.503149  0.546715  0.434636  0.826405    1542    1212
4     0.483683  0.763482  0.973455  0.830068  0.735215    1542    1212
5     0.942042  0.899506  0.711576  0.417602  0.803735    1542    1212
6     0.475248  0.778589  0.994209  0.402726  0.695572    1542    1212
7     0.362965  0.951992  0.746591  0.765661  0.155705    1542    1212
8     0.110497  0.293670  0.636798  0.471073  0.213919    1542    1212
9     0.120797  0.962995  0.842799  0.996153  0.028872    1542    1212

In [57]:
newdf.reset_index()

,index,K,L,M,N,O,"(0, 0)","(0, O)"
0,0,1452.000000,0.198703,0.382484,0.788295,0.746294,1542,1212
1,1,0.871185,0.524304,0.857125,0.644504,0.574060,1542,1212
2,2,0.980907,0.080592,0.495087,0.867326,0.750801,1542,1212
3,3,0.002225,0.503149,0.546715,0.434636,0.826405,1542,1212
4,4,0.483683,0.763482,0.973455,0.830068,0.735215,1542,1212
...,...,...,...,...,...,...,...,...
216,216,0.704472,0.698501,0.711056,0.647427,0.732279,1542,1212
217,217,0.862461,0.213811,0.896249,0.277109,0.673619,1542,1212
218,218,0.815203,0.783656,0.423769,0.064249,0.760220,1542,1212
219,219,0.304523,0.343384,0.519712,0.333602,0.199461,1542,1212
220,220,0.745247,0.409209,0.370460,0.525673,0.931763,1542,1212

In [58]:
newdf.reset_index(drop=True,inplace=True)

In [59]:
newdf.head(45)

              K         L         M         N         O  (0, 0)  (0, O)
0   1452.000000  0.198703  0.382484  0.788295  0.746294    1542    1212
1      0.871185  0.524304  0.857125  0.644504  0.574060    1542    1212
2      0.980907  0.080592  0.495087  0.867326  0.750801    1542    1212
3      0.002225  0.503149  0.546715  0.434636  0.826405    1542    1212
4      0.483683  0.763482  0.973455  0.830068  0.735215    1542    1212
5      0.942042  0.899506  0.711576  0.417602  0.803735    1542    1212
6      0.475248  0.778589  0.994209  0.402726  0.695572    1542    1212
7      0.362965  0.951992  0.746591  0.765661  0.155705    1542    1212
8      0.110497  0.293670  0.636798  0.471073  0.213919    1542    1212
9      0.120797  0.962995  0.842799  0.996153  0.028872    1542    1212
10     0.347991  0.413599  0.951955  0.363915  0.085586    1542    1212
11     0.248939  0.747264  0.925242  0.709734  0.917855    1542    1212
12     0.773369  0.567564  0.029947  0.367097  0.673620    1542    1212
13     0.769936  0.156336  0.260008  0.872167  0.224722    1542    1212
14     0.336830  0.285266  0.739307  0.569935  0.954089    1542    1212
15     0.013804  0.173871  0.900393  0.576953  0.004202    1542    1212
16     0.936496  0.412425  0.506975  0.884618  0.005567    1542    1212
17     0.047628  0.598903  0.214765  0.954617  0.087237    1542    1212
18     0.866904  0.577713  0.317597  0.702022  0.110617    1542    1212
19     0.295589  0.857011  0.240510  0.398333  0.923756    1542    1212
20     0.139985  0.572681  0.908584  0.581269  0.404604    1542    1212
21     0.491388  0.005467  0.854866  0.837118  0.593062    1542    1212
22     0.194456  0.313753  0.289150  0.464659  0.947140    1542    1212
23     0.340087  0.794938  0.283030  0.586504  0.728499    1542    1212
24     0.641471  0.868216  0.528300  0.464208  0.189807    1542    1212
25     0.798240  0.318257  0.085495  0.337505  0.940124    1542    1212
26     0.836622  0.145144  0.171019  0.558830  0.208444    1542    1212
27     0.410306  0.074133  0.506951  0.662617  0.890695    1542    1212
28     0.983501  0.186167  0.680812  0.911507  0.079519    1542    1212
29     0.842867  0.047082  0.732233  0.996254  0.794664    1542    1212
30     0.474754  0.737155  0.185341  0.221632  0.515708    1542    1212
31     0.672854  0.308153  0.524250  0.261896  0.590778    1542    1212
32     0.430457  0.404886  0.576459  0.067514  0.002338    1542    1212
33     0.114114  0.446181  0.557471  0.011312  0.253342    1542    1212
34     0.781063  0.394285  0.464173  0.599724  0.708699    1542    1212
35     0.618141  0.477403  0.075326  0.161343  0.761818    1542    1212
36     0.134124  0.328350  0.331724  0.855685  0.741513    1542    1212
37     0.649666  0.184385  0.506671  0.668087  0.246679    1542    1212
38     0.391446  0.897939  0.607916  0.568916  0.725794    1542    1212
39     0.410279  0.756053  0.497592  0.504926  0.356007    1542    1212
40     0.244371  0.082896  0.306937  0.225758  0.197790    1542    1212
41     0.906536  0.398826  0.123542  0.002609  0.308183    1542    1212
42     0.848892  0.101506  0.601357  0.436890  0.624374    1542    1212
43     0.615855  0.901272  0.804210  0.983387  0.723428    1542    1212
44     0.646629  0.232592  0.743110  0.655378  0.698260    1542    1212

In [60]:
newdf['L'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
216    False
217    False
218    False
219    False
220    False
Name: L, Length: 221, dtype: bool

In [61]:
newdf['B']=None

In [62]:
newdf

               K         L         M         N         O  (0, 0)  (0, O)     B
0    1452.000000  0.198703  0.382484  0.788295  0.746294    1542    1212  None
1       0.871185  0.524304  0.857125  0.644504  0.574060    1542    1212  None
2       0.980907  0.080592  0.495087  0.867326  0.750801    1542    1212  None
3       0.002225  0.503149  0.546715  0.434636  0.826405    1542    1212  None
4       0.483683  0.763482  0.973455  0.830068  0.735215    1542    1212  None
..           ...       ...       ...       ...       ...     ...     ...   ...
216     0.704472  0.698501  0.711056  0.647427  0.732279    1542    1212  None
217     0.862461  0.213811  0.896249  0.277109  0.673619    1542    1212  None
218     0.815203  0.783656  0.423769  0.064249  0.760220    1542    1212  None
219     0.304523  0.343384  0.519712  0.333602  0.199461    1542    1212  None
220     0.745247  0.409209  0.370460  0.525673  0.931763    1542    1212  None

[221 rows x 8 columns]

In [63]:
newdf['L'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
216    False
217    False
218    False
219    False
220    False
Name: L, Length: 221, dtype: bool

In [64]:
newdf.loc[:, ['L']]=221

newdf

In [65]:
newdf.head(10)

             K      L         M         N         O  (0, 0)  (0, O)     B
0  1452.000000  221.0  0.382484  0.788295  0.746294    1542    1212  None
1     0.871185  221.0  0.857125  0.644504  0.574060    1542    1212  None
2     0.980907  221.0  0.495087  0.867326  0.750801    1542    1212  None
3     0.002225  221.0  0.546715  0.434636  0.826405    1542    1212  None
4     0.483683  221.0  0.973455  0.830068  0.735215    1542    1212  None
5     0.942042  221.0  0.711576  0.417602  0.803735    1542    1212  None
6     0.475248  221.0  0.994209  0.402726  0.695572    1542    1212  None
7     0.362965  221.0  0.746591  0.765661  0.155705    1542    1212  None
8     0.110497  221.0  0.636798  0.471073  0.213919    1542    1212  None
9     0.120797  221.0  0.842799  0.996153  0.028872    1542    1212  None

In [66]:
df = pd.DataFrame(
    {
        "name": ["Alfred", "Batman", "Catwoman"],
        "toy": [np.nan, "Batmobile", "Bullwhip"],
        "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    }
)

In [67]:
df.head()

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [68]:
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [69]:
df.drop_duplictes(subset=['name'],keep= False)

AttributeError: 'DataFrame' object has no attribute 'drop_duplictes'

In [ ]:
df.shape

In [ ]:
df.info()


                                                   #practice code

In [ ]:

data = {
    "day": [1,2,3,4,5],
    "sales": [1200, 1500, 900, 1800, 2000]
}

df = pd.DataFrame(data)

print(df)
print("Average sales:", df["sales"].mean())
print("Max sales:", df["sales"].max())

In [ ]:
data={
    "name":["krunal","jayraj","jaimin","ajay","ravi"],
    "marks":[50,20,30,40,45]
}

df=pd.DataFrame(data)

print(df)
print("Avarage marks",df["marks"].mean())
print("Max marks",df["marks"].max())

In [ ]:
topper = df[df["marks"]== df["marks"].max()]
print("Topper is:")
print(topper)

In [ ]:
lowest = df[df["marks"] == df["marks"].min()]
print("lowest is :")
print(lowest)

In [ ]:
data = {
    "name":["royal","krunal","chavda"],
    "city":["ahmedabad","mumbai","london"]
}

df=pd.DataFrame(data)
print(df)
print(df["city"])
print(df["name"])
print(df["city"].unique())

In [ ]:
import pandas as pd

In [ ]:
data={
    "thing":["books","code","laptop","computer"],
    "price":[120,100,51500,52000]
}
df = pd.DataFrame(data)
print(df)
print("Avarage price",df["price"].mean()) 
print("Max price",df["price"].max())
print("Unique thing only one",df["thing"].unique())

In [ ]:
data={
    "thing":["laptop","bag","cloths","rubber","computer","code"],
    "cost_price":[50,60,55,76,78,80],
    "selling_price":[75,70,95,120,90,100]
}
df=pd.DataFrame(data)

In [ ]:
df

In [ ]:
df["profit"]=df["selling_price"]-df["cost_price"]

In [ ]:
df

In [ ]:
df["profit_percent"]=df["profit"]/df["cost_price"]*100

In [ ]:
df

In [ ]:
print("selling_price",df["selling_price"].mean())
print("selling_price",df["selling_price"].min())
print("selling_price",df["selling_price"].max())
print("selling_price",df["selling_price"].median())

In [ ]:
df

In [ ]:
avg_price=df["selling_price"].mean()
df["category"]=df["selling_price"].apply(lambda x:"expensive"
if x>avg_price
                                         else "cheap")

df

In [ ]:
df["price_normalized"]=(df["selling_price"]-df["selling_price"].min()
)/(
    df["selling_price"].max() - df["selling_price"].min())

In [ ]:
df

In [ ]:
total_price=df["selling_price"].sum()
df["sales_price_%"]=(df["selling_price"]/total_price)*100

In [ ]:
df

In [ ]:
df.groupby("category")["selling_price"].agg(
    ["count","mean","max","min"]
)

In [ ]:
a=pd.Series([1,2,3,4,5,6])
print(a)

In [ ]:
s=pd.Series([1,2,3] , index=["A","B","C"])
print(s["C"]) 
print(s["B"])

In [71]:
data={
    "Department":["it","it","ce","ce"],
    "Salary":[20000,25000,30000,15000]
}
df=pd.DataFrame(data)
print(df)

  Department  Salary
0         it   20000
1         it   25000
2         ce   30000
3         ce   15000
Department
ce    22500.0
it    22500.0
Name: Salary, dtype: float64

In [73]:
print(df.groupby("Department")["Salary"].mean())
print(df.groupby("Department")["Salary"].max())
print(df.groupby("Department")["Salary"].sum())

Department
ce    22500.0
it    22500.0
Name: Salary, dtype: float64
Department
ce    30000
it    25000
Name: Salary, dtype: int64
Department
ce    45000
it    45000
Name: Salary, dtype: int64

In [77]:
print(df.sort_values("Salary"))

  Department  Salary
3         ce   15000
0         it   20000
1         it   25000
2         ce   30000

In [87]:
data={
    "name":["krunal","ajay","ravi","anand"],
    "marks":[95,85,np.nan,np.nan]
}
df=pd.DataFrame(data)
print(df.isnull()) #missing value find kare
print(df.isnull().sum()) #missing count value kare

    name  marks
0  False  False
1  False  False
2  False   True
3  False   True
name     0
marks    2
dtype: int64

In [88]:
print(df.dropna())

     name  marks
0  krunal   95.0
1    ajay   85.0

In [93]:
print(df.fillna(12))
print(df.fillna(13))

     name  marks
0  krunal   95.0
1    ajay   85.0
2    ravi   12.0
3   anand   12.0
     name  marks
0  krunal   95.0
1    ajay   85.0
2    ravi   13.0
3   anand   13.0

In [95]:
print({
    "name":"ravi",
    "marks":55
})

{'name': 'ravi', 'marks': 55}

In [96]:
print({
    "name":"anand",
    "marks":50
})

{'name': 'anand', 'marks': 50}

In [99]:
print(df["marks"].fillna(df["marks"].mean(), inplace=True))

0    95.0
1    85.0
2    90.0
3    90.0
Name: marks, dtype: float64

C:\Users\kruna\AppData\Local\Temp\ipykernel_12156\4001219981.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  print(df["marks"].fillna(df["marks"].mean(), inplace=True))

In [108]:
print(df.ffill())

     name  marks
0  krunal   95.0
1    ajay   85.0
2    ravi   85.0
3   anand   85.0

In [109]:
print(df.bfill())

     name  marks
0  krunal   95.0
1    ajay   85.0
2    ravi    NaN
3   anand    NaN